---
title: "Relaxed Lasso Glmnet Simulation"
author: "Alexander Romanus"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) { 
      out_dir <- '/results/knits';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, paste(runif(1), 'relaxed_simulation.html'))) })
output:
  html_document: 
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
library(casebase)
library(future.apply)
library(glmnet)
#library(mtool)
library(parallelly)
library(timereg)
library(parallel)
library(tictoc)
library(tidyverse)
#library(riskRegression)
library(cmprsk)
library(survsim)
library(caret)
library(Matrix)
library(dplyr)

# Helper functions 
source("../src/helper_functions.R")
```

# Check final implementation
``` {r test-relaxed-lasso-final}
p = 20
n = 400

dataset = generateDataset(p, n)
partitioned_data = partitionData(dataset$X, dataset$Y)
training_data = partitioned_data[c("x_train", "y_train")]

# print(head(training_data$x_train))
# print(head(training_data$y_train))

result = myRelaxedFinal(training_data$x_train, training_data$y_train)
print(result$best_fit$coefficients)

relaxed_fit = cv.glmnet(training_data$x_train, training_data$y_train, gamma = 0, nfolds = 5, relax = TRUE)
print(relaxed_fit$glmnet.fit$relaxed$beta[, relaxed_fit$index[1]])
```

# Run simulation
``` {r run-sim, warning = FALSE, echo = FALSE, eval=FALSE}
N = 500
tic()
sim_results = runSim(20, 400, N, FALSE)
cat(paste("Time to compute ", as.character(N), " iterations: ", toc()))
```


# Results from N = 1000 simulation

## Coefficient Biases

``` {r resulting-coefficients, echo=FALSE, eval=FALSE}
formatCoefficientBiasTable(sim_results)
```

## Average Test MSEs

``` {r resulting-MSEs, echo=FALSE, eval=FALSE}
formatAverageTestMSETable(sim_results)
```

# Survival simulation N = 5, n = 400, p = 20: initial results
``` {r relaxed-lasso-glmnet-cv-results, echo=FALSE, eval = FALSE}
# results_table = runCasebaseSim(400, 20, 5)
# summarized_sim_casebase_table = formatCaseBaseTable(results_table)
# summarized_sim_casebase_table
formatted_table
```

