---
title: "Research: Things to Do List"
author: "Nirupama Tamvada"
format: pdf
editor: visual
---

## Things to do

1.  Reproduce results in Binder et al., 2016 paper for standard variable selection case and also for high-dimensional case for binomial model - for lasso, elastic net and adaptive LASSO
    -   Look at data generation process - if necessary email authors for script - generate both proportional hazards as well as sub-distribution model

    -   Replicate to a t- 1000 simulations on compute canada

    -   Check if using lambda.min or lambda.1se - BY THIS WEEKEND FOCUS ON REPRODUCING BINOMIAL MODEL RESULTS FIRST

    -   Look into how to reproduce the block correlation structure
2.  Data generation process for my simulations - look at Tapak et al., 2022 decide on a final function and finalize - test this function: test high-dimensional cases
3.  Sampling weights for the likelihood for non-cases: figure out how to implement, adaptive LASSO for casebase
4.  Prediction error - figure out how to compute for casebase
5.  Implement all competing models: cause-specific hazard models, boosted fine-gray, non-parametric (Tapak et al., 2022), quantile regression for competing risks, binomial model, penalized fine-gray model
6.  Look into case-base sampling further- math details + oracle property of adaptive LASSO

## Simulation settings

-   High-dimensional (p = 1000, N = 400, 500)

    -   Independent, AR1 correlation structure, block correlation structure

-   Performance variation with increasing censoring as well
